insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('USD','美金');
insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('TWD','台幣');
insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('JPY','日圓');
insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('HKD','港幣');
insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('GBP','英鎊');
insert into CURRENCY(CURRENCY_CODE,CURRENCY_NAME) VALUES('EUR','歐元');