CREATE TABLE CURRENCY (
    SEQ_ID INT PRIMARY KEY AUTO_INCREMENT,
    CURRENCY_CODE VARCHAR(4) NOT NULL ,
    CURRENCY_NAME VARCHAR(100) NOT NULL, 
    UNIQUE KEY CURRENCY_CODE_UNIQUE (CURRENCY_CODE)  
);